# Sidebar navigation

- label: 'Hello World'
  link: '/'
- label: ''
  link: ''
- label: COBOLISH
  items:
    - label: 'EXIT PERFORM'
      link: '/usage/exit-perform'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
